---
- name: Pull docker image && start app
  hosts: all
  become: true
  tasks:
    - name: Start container
      docker_container:
        name: reddit
        image: motek/otus-reddit:1.0
        state: started
        ports: "9292:9292"
